export enum AutomationStep {
  QUEUED = "QUEUED",
  STARTING = "STARTING",
  LAUNCH_BROWSER = "LAUNCH_BROWSER",
  OPEN_JOB = "OPEN_JOB",
  UPLOAD_RESUME = "UPLOAD_RESUME",
  FILL_PROFILE = "FILL_PROFILE",
  FILL_CUSTOM_QUESTIONS = "FILL_CUSTOM_QUESTIONS",
  UPLOAD_COVER_LETTER = "UPLOAD_COVER_LETTER",
  REVIEW = "REVIEW",
  WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL",
  SUBMITTING = "SUBMITTING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED"
}
